### ISSUE TITLE
Error in if (a == b) { : the condition has length > 1

### ISSUE THREAD

**Issue by bbb801** [skent259/rsmatch#21]
Dear Sir/Madam,

I am trying to apply your tool to my data. I have some issues.

'diff_admit_hours' is the time for admission to the hospital, not integer but numeric. 'startdrug_hours' is the time to take the drugs, some have the same values for the same ID. May I know if the 'trt_time' should be set as NA for those who are not treated? I have tried both ways and there are errors like below:

error 1: trt_time is not NA for different treatments.
> drug2<-drug%>%select(all_of(select_cols))
> drug_test<-drug2[1:100,]%>%select(all_of(select_cols))
> pairs <- coxpsmatch(
+   n_pairs = 5,
+   data = drug_test,
+   covariates=covars,
+   id = "subject_id", time = 'diff_admit_hours', trt_time = "startdrug_hours"
+ )
Error in if (a == b) { : the condition has length > 1

error 2: when I set trt_time as NA for those who are not treated.
Error in `$<-.data.frame`(`*tmp*`, "p", value = c(-1.23439407919853e-10,  : 
  The replacement data has 80 rows, but the data has 492064 rows.

Any sgestions?

**Comment by skent259** [comment]
Hi, a couple of things

1. The `trt_time` variable should be the exact same for each `id`, because each subject should only have one treatment time. 
2. The package was not originally built for continuous `time` variables. It was built and testing on longitudinal data where there are discrete `time`s. 
3. In general, `trt_time` should be NA for those that are never treated. 

With that said, it's very difficult to debug without a reproducible dataset or example. Can you provide one? It doesn't have to be real data if your data is confidential, just something with a similar format that gives you the same errors. 

My guess would be that your data might not be in the right format for these methods. Especially if point 1 above is not true.

**Comment by bbb801** [comment]
Thank you for your patience and detailed comments. What about 'time'? Is it the admission time or the survival outcome time? I have provided the sample data below. The outcome is the 'stroke' and its competing outcome--'mortality'.  'diff_admit_hours' is the admission time to the hospital. 'stroke' occurs during the hospitalisation. 'surv_row_hours' is the time for outcomes of discharge, for 'mortality'.  'startdrug_hours' is the time for tcm treatment. I would like to obtain pairs by treatment to finally compute the stroke & survival between the pairs. 
[drug_filtered3_test.csv](https://github.com/skent259/rsmatch/files/14504421/drug_filtered3_test.csv)

According to your suggestions that 'time' should be an integer. Is it meaningful that I replace my continuous and uneven 'time' with integers? I can also delete more rows which does not indicate tcm treatment for the same id and same 'trt_time'. But I am not sure if it is meaningful in order to use your tools.

Actually data is from MIMIC IV hospital datasets where there is subject ID and admission ID. It seems the id should use admission ID in order to keep a different treatment for the same subject ID. In that case, it might select pairs from the same subject.

My example codes:
drug <-drug %>%
  mutate(across(c(subject_id), as.character),
         across(c(treatment, marital_status, race, gender, mortality, stroke), as.factor),
         across(c(anchor_age, surv_row_hours, diff_admit_hours,  startdrug_hours), as.numeric))
covars<-c("subject_id","marital_status", "race", "gender", "anchor_age",
           'startdrug_hours','diff_admit_hours')
pairs <- coxpsmatch(
  n_pairs = 5,
  data = drug,
  covariates=covars,
  id = "subject_id", time = 'diff_admit_hours', trt_time = "startdrug_hours"
)

**Comment by skent259** [comment]
I don't think the methods in this package will help for your data, now that I see the full context. I would not recommend trying to change your data to get the function to run.

I still don't completely understand what the different rows for each subject are, but for risk set matching, it is based on a fixed visit schedule or something similar. Think a patient coming in every 4 weeks for some testing. This is not the structure of your data. You also don't really have time-dependent covariates except maybe drug_cat.

You may be able to accomplish your goal by just doing straightforward matching on the covariates based on each row. Your times are also more like covariates in this situation I think, and can be used for matching. But I'm not an expert on your particular data or the objectives of your analysis.

**Comment by bbb801** [comment]
Thank you. Do you mean my data should be time series data with even time intervals? My data is longitudinal data, with uneven repeated measurements. I also tried to preprocess my data as in Oasis data. However, I still had errors. I simplfied my data and uploaded it here.

pairs <- coxpsmatch(
  n_pairs = 548,
  data = d
  id = "subject_id", time = "visit", trt_time = "trt_time2"
)

[demo2.csv](https://github.com/skent259/rsmatch/files/14818444/demo2.csv)

**Comment by skent259** [comment]
Can you show what errors you get now? You may find the {reprex} R package helpful for this. One guess is that you have too many pairs. I count 371 rows with non NA "trt_time2" which means the number of subjects possible for matching is definitely less than 371, but you want 548 pairs, which is impossible. Also possible that the lack of any time-varying covariates is causing trouble. You only have baseline covariates, which calls into question whether risk set matching is needed.

The main problem with the previous data is not the uneven time intervals. The problem is that risk set matching needs to match one treated subject to a "not yet treated or never treated (control)" subject but this matching happens at the time of treatment for the treated subject. That is, the matched control must have **observed, time-dependent information available at the time the treated subject was treated**. This only happens when the trt_times are somewhat repeated as times in the data, which doesn't appear to be the case here

I would really recommend reading the paper by Li, Propert & Rosenbaum to understand the type of matching that's going on in this package
