### ISSUE TITLE
Difference and format between time & trt_time

### ISSUE THREAD

**Issue by bbb801** [skent259/rsmatch#22]
Dear Sir or Madam,

I would like to know more about  'time' & 'trt_time' in 'coxpsmatch' function. Take the following figure codes as an example: in oasis data, visit is used as 'time' and time_of_ad is as 'trt_time'. 'time' is the same as the row num in each subject group, i.e., a subject who has n visits has  'time' ranging from 1 to n. What about 'trt_time'? Should it be integer for the treatment? Is it larger or equal to  'time'? Is there a relationship between 'time' & 'trt_time'?

<img width="339" alt="image" src="https://github.com/skent259/rsmatch/assets/52306405/01503d65-e2ef-4762-82b6-8a98272b0018">

**Comment by skent259** [comment]
The `trt_time` should match exactly to one of the `time`s for the particular `id`. 

For example in the oasis data, for one subject (OAS2_0007) we have records for them at times 1, 3, and 4. So `trt_time` must be either 1, 3, or 4. In this case, it is 3. The risk set methods (including `coxpsmatch()`) essentially use a panel data setting, where subjects are observed at discrete time points (maybe every 4 weeks, or every day, etc). 

It actually doesn't matter that the treatment is an integer, or that the numbers follow exactly 1 to n. But the `time`s (and consequently `trt_time`s) must come from a discrete set. And they must have overlap the times of other `id`s (e.g. subjects), otherwise they will never be matched. This is how the risk set matching works, of which `coxpsmatch()` is one method.
